About section static
front-end-by-rimantas/31-grupe-portfolio-daniels pull request #15
Opened 2021-10-29 18:39 UTC by ImantasCe

prachekinkit ir jei pamatysit ką nors negero, pakomentuokit

2021-10-31 16:20 UTC, simonachess requested changes
col-sm-12, col-md-4 tas klases reikia palikti, kad veiktu responsive

2021-11-02 16:33 UTC, simonachess approved these changes

2021-11-02 16:34 UTC, ImantasCe commented
@Mokslams užmesk akį į kreivos rankos kodą

2021-11-02 16:35 UTC, Mokslams approved these changes
Kaip ir gerai

2021-11-02 16:39 UTC, merged